name: crafter-appo-baseline

global_settings:
  use_wandb: False

experiment_settings:
  save_every_sec: 120
  train_for_env_steps: 100000000

async_ppo:

  experiment_summaries_interval: 5
  ppo_epochs: 1
  batch_size: 1024
  worker_num_splits : 1
  use_rnn: True
  max_grad_norm: 0.0
  num_workers: 1
  num_envs_per_worker: 2

environment:
  name: "MineRLTreechop-v0"